### ISSUE TITLE
How to obtain 'omniglot.mat'?

### ISSUE THREAD

**Issue by Linear95** [mingzhang-yin/ARM-gradient#1]
When I try to run b_omni_arm.py, I find 'omniglot.mat' is needed in the current directory. However, the online Omniglot dataset does not have a file named 'omniglot'. So can you offer the link or show how to obtain the correct form of the data?

**Comment by mingzhang-yin** [comment]
Thanks for reminding! I have uploaded the file. The OMNIGLOT data is also available publicly(google it you will find)
